config/routes.rb
Rails.application.routes.draw do
  root to: "staticpages#index"

  resources :users, only: [:new, :create, :edit, :update]
  get "auth/facebook/callback", to: "omniauth#facebook"

  namespace :api, defaults: { format: :json } do
    resource  :session, only: [:show, :create, :destroy]
    resources :categories, only: [:index, :create, :destroy, :edit]
    resources :feeds, only: [:create, :show, :index,]
    resources :searches, only: [:index]

    get ':feeds/:action/:category_id',
      controller: "feeds"
    get ':feeds/today/:action',
      controller: "feeds"
    get ':feeds/read/:action',
      controller: "feeds"
    get ':feeds/refresh/:action',
      controller: "feeds"
    get ':subscriptions/:action/:category_id/:feed_id',
      controller: "subscriptions"
    post ':subscriptions/:action/:category_id/:feed_id',
      controller: "subscriptions"
    get ':reads/:action',
      controller: "reads"
  end
end

app/views/shared/_header.html.erb
<header>
  <h1 class="logo">NewsJunkie</h1>
</header>

app/views/shared/_login_errors.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <p class="error">
    <%= error %>
  </p>
  <% end %>
<% end %>

app/views/shared/_login_form.html.erb
<% action = (new_user ? users_url : session_url) %>
<% button_text = (new_user ? "Sign Up" : "Login") %>

<form action="<%= action %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="text"
    name="user[email]"
    placeholder="Email"
    class="auth-email">

  <input
    type="password"
    name="user[password]"
    placeholder="Password"
    class="auth-password">

  <input type="submit" value="<%= button_text %>" class="auth-submit">
</form>